### ISSUE TITLE
[Modfiy요청] 댓글 목록 조회 API 응답 값 추가

### ISSUE THREAD

**Issue by Dolphin-PC** [bocho-drive/back#84]
@young219257 
- [x] `GET` `/comments` API 응답값 추가 요청드립니다.
  - userId

**Comment by Dolphin-PC** [comment]
@young219257 
- [ ]  `GET` `/comments` API 응답값 추가 요청드립니다.
  - 작성자 이름(author)

**Comment by young219257** [comment]
추가했습니다.
